name: Wrap CI for macOS

on: [push, pull_request]

jobs:
  build:
    name: Tests for 🐍 ${{ matrix.python_version }}
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        python_version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          brew install cmake ninja boost

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python_version: ${{ matrix.python_version }}

      - name: Python Dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Build and Test
        run: |
          cd tests
          # Use Pytest to run all the tests.
          pytest
